/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '1/3/17 4:34 PM' with Gradle 2.3
 *
 * @author Webonise, @date 1/3/17 4:34 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
